version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: development-postgres
    ports:
      # Port 5000 on my machine will point to postgres running inside the container
      - "5000:5432"
    environment:
      POSTGRES_DB: dddforum
      POSTGRES_USER: dddforum_user
      POSTGRES_PASSWORD: dddforum_password
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local